image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Build artifact
        script:
          - mkdir artifact
          - echo "Pipelines is awesomse!" > artifact/index.html
        artifacts:
          - artifact/*
    - step:
        name: Deploy to S3
        deployment: staging
        script:
          - pipe: atlassian/aws-s3-deploy:0.3.8
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'eu-west-2'
              S3_BUCKET: 'veri-bitbucket-codedeploy-deployment'
              LOCAL_PATH: 'artifact'
              ACL: 'public-read'
